#import "LanSongProgram.h"

// Base classes
#import "LanSongContext.h"
#import "LanSongOutput.h"
#import "LanSongVideoCamera.h"
#import "LanSongStillCamera.h"
#import "LanSongPicture.h"
#import "LanSongRawDataInput.h"
#import "LanSongRawDataOutput.h"
#import "LanSongFilterPipeline.h"
#import "LanSongTextureOutput.h"
#import "LanSongFilterGroup.h"
#import "LanSongTextureInput.h"
#import "LanSongUIElement.h"
#import "LanSongBuffer.h"
#import "LanSongFramebuffer.h"
#import "LanSongFramebufferCache.h"

// Filters
#import "LanSongFilter.h"
#import "LanSongTwoInputFilter.h"
#import "LanSongPixellateFilter.h"
#import "LanSongPixellatePositionFilter.h"
#import "LanSongSepiaFilter.h"
#import "LanSongColorInvertFilter.h"
#import "LanSongSaturationFilter.h"
#import "LanSongContrastFilter.h"
#import "LanSongExposureFilter.h"
#import "LanSongBrightnessFilter.h"
#import "LanSongLevelsFilter.h"
#import "LanSongSharpenFilter.h"
#import "LanSongGammaFilter.h"
#import "LanSongSobelEdgeDetectionFilter.h"
#import "LanSongSketchFilter.h"
#import "LanSongToonFilter.h"
#import "LanSongSmoothToonFilter.h"
#import "LanSongMultiplyBlendFilter.h"
#import "LanSongDissolveBlendFilter.h"
#import "LanSongKuwaharaFilter.h"
#import "LanSongKuwaharaRadius3Filter.h"
#import "LanSongVignetteFilter.h"
#import "LanSongGaussianBlurFilter.h"
#import "LanSongGaussianBlurPositionFilter.h"
#import "LanSongGaussianSelectiveBlurFilter.h"
#import "LanSongOverlayBlendFilter.h"
#import "LanSongDarkenBlendFilter.h"
#import "LanSongLightenBlendFilter.h"
#import "LanSongSwirlFilter.h"
#import "LanSongSourceOverBlendFilter.h"
#import "LanSongColorBurnBlendFilter.h"
#import "LanSongColorDodgeBlendFilter.h"
#import "LanSongScreenBlendFilter.h"
#import "LanSongExclusionBlendFilter.h"
#import "LanSongDifferenceBlendFilter.h"
#import "LanSongSubtractBlendFilter.h"
#import "LanSongHardLightBlendFilter.h"
#import "LanSongSoftLightBlendFilter.h"
#import "LanSongColorBlendFilter.h"
#import "LanSongHueBlendFilter.h"
#import "LanSongSaturationBlendFilter.h"
#import "LanSongLuminosityBlendFilter.h"
#import "LanSongCropFilter.h"
#import "LanSongGrayscaleFilter.h"
#import "LanSongTransformFilter.h"
#import "LanSongChromaKeyBlendFilter.h"
#import "LanSongHazeFilter.h"
#import "LanSongLuminanceThresholdFilter.h"
#import "LanSongPosterizeFilter.h"
#import "LanSongBoxBlurFilter.h"
#import "LanSongAdaptiveThresholdFilter.h"
#import "LanSongSolarizeFilter.h"
#import "LanSongUnsharpMaskFilter.h"
#import "LanSongBulgeDistortionFilter.h"
#import "LanSongPinchDistortionFilter.h"
#import "LanSongCrosshatchFilter.h"
#import "LanSongCGAColorspaceFilter.h"
#import "LanSongPolarPixellateFilter.h"
#import "LanSongStretchDistortionFilter.h"
#import "LanSongPerlinNoiseFilter.h"
#import "LanSongJFAVoronoiFilter.h"
#import "LanSongVoronoiConsumerFilter.h"
#import "LanSongMosaicFilter.h"
#import "LanSongTiltShiftFilter.h"
#import "LanSong3x3ConvolutionFilter.h"
#import "LanSongEmbossFilter.h"
#import "LanSongCannyEdgeDetectionFilter.h"
#import "LanSongThresholdEdgeDetectionFilter.h"
#import "LanSongMaskFilter.h"
#import "LanSongMaskBlendFilter.h"




#import "LanSongHistogramFilter.h"
#import "LanSongHistogramGenerator.h"
#import "LanSongHistogramEqualizationFilter.h"
#import "LanSongPrewittEdgeDetectionFilter.h"
#import "LanSongXYDerivativeFilter.h"
#import "LanSongHarrisCornerDetectionFilter.h"
#import "LanSongAlphaBlendFilter.h"
#import "LanSongNormalBlendFilter.h"
#import "LanSongNonMaximumSuppressionFilter.h"
#import "LanSongRGBFilter.h"
#import "LanSongMedianFilter.h"
#import "LanSongBilateralFilter.h"
#import "LanSongCrosshairGenerator.h"
#import "LanSongToneCurveFilter.h"
#import "LanSongNobleCornerDetectionFilter.h"
#import "LanSongShiTomasiFeatureDetectionFilter.h"
#import "LanSongErosionFilter.h"
#import "LanSongRGBErosionFilter.h"
#import "LanSongDilationFilter.h"
#import "LanSongRGBDilationFilter.h"
#import "LanSongOpeningFilter.h"
#import "LanSongRGBOpeningFilter.h"
#import "LanSongClosingFilter.h"
#import "LanSongRGBClosingFilter.h"
#import "LanSongColorPackingFilter.h"
#import "LanSongSphereRefractionFilter.h"
#import "LanSongMonochromeFilter.h"
#import "LanSongOpacityFilter.h"
#import "LanSongHighlightShadowFilter.h"
#import "LanSongFalseColorFilter.h"
#import "LanSongHSBFilter.h"
#import "LanSongHueFilter.h"
#import "LanSongGlassSphereFilter.h"
#import "LanSongLookupFilter.h"
#import "LanSongAmatorkaFilter.h"
#import "LanSongMissEtikateFilter.h"
#import "LanSongSoftEleganceFilter.h"
#import "LanSongAddBlendFilter.h"
#import "LanSongDivideBlendFilter.h"
#import "LanSongPolkaDotFilter.h"
#import "LanSongLocalBinaryPatternFilter.h"
#import "LanSongColorLocalBinaryPatternFilter.h"
#import "LanSongLanczosResamplingFilter.h"
#import "LanSongAverageColor.h"
#import "LanSongSolidColorGenerator.h"
#import "LanSongLuminosity.h"
#import "LanSongAverageLuminanceThresholdFilter.h"
#import "LanSongWhiteBalanceFilter.h"
#import "LanSongChromaKeyFilter.h"
#import "LanSongLowPassFilter.h"
#import "LanSongHighPassFilter.h"
#import "LanSongMotionDetector.h"
#import "LanSongHalftoneFilter.h"
#import "LanSongThresholdedNonMaximumSuppressionFilter.h"
#import "LanSongHoughTransformLineDetector.h"
#import "LanSongParallelCoordinateLineTransformFilter.h"
#import "LanSongThresholdSketchFilter.h"
#import "LanSongLineGenerator.h"
#import "LanSongLinearBurnBlendFilter.h"
#import "LanSongGaussianBlurPositionFilter.h"
#import "LanSongPixellatePositionFilter.h"
#import "LanSongTwoInputCrossTextureSamplingFilter.h"
#import "LanSongPoissonBlendFilter.h"
#import "LanSongMotionBlurFilter.h"
#import "LanSongZoomBlurFilter.h"
#import "LanSongLaplacianFilter.h"
#import "LanSongiOSBlurFilter.h"
#import "LanSongLuminanceRangeFilter.h"
#import "LanSongDirectionalNonMaximumSuppressionFilter.h"
#import "LanSongDirectionalSobelEdgeDetectionFilter.h"
#import "LanSongSingleComponentGaussianBlurFilter.h"
#import "LanSongThreeInputFilter.h"
#import "LanSongFourInputFilter.h"
#import "LanSongWeakPixelInclusionFilter.h"
#import "LanSongColorConversion.h"
#import "LanSongColourFASTFeatureDetector.h"
#import "LanSongColourFASTSamplingOperation.h"


//2017年10月19日15:48:35新增:

#import "LanSongBeautyFilter.h"

#import "LanSongIFFilter.h"  //LanSongIFFilter是所有IF开头的类的父类, 只是用来被继承, 不能直接使用.


#import "LanSongIF1977Filter.h"
#import "LanSongIFAmaroFilter.h"
#import "LanSongIFBrannanFilter.h"
#import "LanSongIFEarlybirdFilter.h"
#import "LanSongIFHefeFilter.h"
#import "LanSongIFHudsonFilter.h"
#import "LanSongIFInkwellFilter.h"
#import "LanSongIFLomofiFilter.h"
#import "LanSongIFNashvilleFilter.h"
#import "LanSongIFRiseFilter.h"
#import "LanSongIFSierraFilter.h"
#import "LanSongIFSutroFilter.h"
#import "LanSongIFToasterFilter.h"
#import "LanSongIFValenciaFilter.h"
#import "LanSongIFWaldenFilter.h"
#import "LanSongIFXproIIFilter.h"
#import "LanSongIFLordKelvinFilter.h"


//2018年03月07日11:23:12 增加
#import "LanSongBeautyTuneFilter.h"
/*
 去燥,磨皮;
 */
#import "LanSongBeautyAdvanceFilter.h"

//2018年04月05日12:20:26 增加
#import "LanSongColorEdgeFilter.h"   //抖音的颜色偏移效果, 滤镜;
#import "LanSongMirrorFilter.h"  //镜像;

